#import <Foundation/Foundation.h>
#import "BJObject.h"

/**
* 柏九后端接口
* ## 错误规则 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol BJTestResponse
@end

@interface BJTestResponse : BJObject

/* 返回你说的话 [optional]
 */
@property(nonatomic) NSString* myWord;
/* 返回一个计数 [optional]
 */
@property(nonatomic) NSNumber* count;

@end
