swagger: '2.0'

info:
  version: "0.0.1"
  title: 柏九后端接口
  description: |
    ## 错误规则

host: work.laiyijie.me:36512
basePath: /server/api/v1/

produces:
  - application/json

schemes:
  - http
tags:
    - name: Test
      description: 测试接口

paths:
  /test/info:
    get:
      tags:
        - Test
      summary: 测试接口
      parameters:
        - name: word
          in: query
          description: 你想说的话
          required: true
          type: string
      responses:
        200:
          description: 回复你的信息
          schema:
            title: TestResponse
            type: object
            properties:
              myWord:
                type: string
                description: 返回你说的话
              count:
                type: integer
                format: int64
                description: 返回一个计数
                


        
