swagger: '2.0'

info:
  version: "0.0.1"
  title: 柏九后端接口
  description: |
    ## 错误规则
    #### 1. 抛错 httpstatus 为 417 会返回 BusinessException的error，包含errorCode 和 errorMessage
    #### 2. 抛错 httpstatus 为 420 是用户未登陆

host: work.laiyijie.me
basePath: /server/api/v1/

produces:
  - application/json
consumes:
  - application/json
  - application/x-www-form-urlencoded

schemes:
  - http
tags:
    - name: User
      description: 会员个人信息接口
    - name: UserAuth
      description: 会员登录接口
    - name: Test
      description: 测试接口

paths:
  /user/test:
    get:
      tags:
        - Test
      summary: 测试接口
      parameters:
        - name: word
          in: query
          description: 你想说的话
          required: true
          type: string
      responses:
        200:
          description: 回复你的信息
          schema:
            title: TestResponse
            type: object
            properties:
              myWord:
                type: string
                description: 返回你说的话
              count:
                type: integer
                format: int64
                description: 返回一个计数
                


        
  