#import <Foundation/Foundation.h>

@class BJApiClient;

/**
* 柏九后端接口
* ## 错误规则 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@protocol BJApi <NSObject>

@property(readonly, nonatomic, strong) BJApiClient *apiClient;

-(instancetype) initWithApiClient:(BJApiClient *)apiClient;

-(void) setDefaultHeaderValue:(NSString*) value forKey:(NSString*)key;
-(NSString*) defaultHeaderForKey:(NSString*)key;

-(NSDictionary *)defaultHeaders;

@end
