/**
 * 柏九后端接口
 * ## 错误规则 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TestResponse {
    /**
     * 返回你说的话
     */
    "myWord"?: string;
    /**
     * 返回一个计数
     */
    "count"?: number;
}

