/**
 * 柏九后端接口
 * ## 错误规则 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering */

export class TestApi {
    protected basePath = 'http://work.laiyijie.me:36512/server/api/v1/';
    public defaultHeaders : any = {};

    static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

    constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
        if (basePath !== undefined) {
            this.basePath = basePath;
        }
    }

    /**
        * 测试接口
        * 
        * @param word 你想说的话
        */
    public testInfoGet (word: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.TestResponse> {
        const localVarPath = this.basePath + '/test/info';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'word' is not null or undefined
        if (word === null || word === undefined) {
            throw new Error('Required parameter word was null or undefined when calling testInfoGet.');
        }
        if (word !== undefined) {
            queryParameters['word'] = word;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
}
