#import <Foundation/Foundation.h>
#import "BJTestResponse.h"
#import "BJApi.h"

/**
* 柏九后端接口
* ## 错误规则 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface BJTestApi: NSObject <BJApi>

extern NSString* kBJTestApiErrorDomain;
extern NSInteger kBJTestApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(BJApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 测试接口
/// 
///
/// @param word 你想说的话
/// 
///  code:200 message:"回复你的信息"
///
/// @return BJTestResponse*
-(NSURLSessionTask*) testInfoGetWithWord: (NSString*) word
    completionHandler: (void (^)(BJTestResponse* output, NSError* error)) handler;



@end
